# Generated by Django 5.0.1 on 2024-01-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(default='<django.db.models.fields.IntegerField><django.db.models.fields.IntegerField>', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.IntegerField(default=0),
        ),
    ]
