# Generated by Django 5.0.1 on 2024-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_album_id_song_song_id_song_track_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(default='<django.db.models.fields.IntegerField><django.db.models.fields.IntegerField>', editable=False, max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.IntegerField(),
        ),
    ]
