# Generated by Django 5.0.1 on 2024-01-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('album_id', models.IntegerField()),
                ('track_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=256)),
                ('song_id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
