# Generated by Django 5.0.1 on 2024-04-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=45)),
                ('path', models.CharField(max_length=256)),
                ('downloadable_artwork', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(null=True)),
                ('ip', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=65)),
                ('track_number', models.IntegerField()),
                ('song_id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False)),
                ('audio_file_name', models.CharField(max_length=65)),
                ('tab_file_name', models.CharField(blank=True, default='', max_length=65)),
                ('lyric_sheet_file_name', models.CharField(blank=True, default='', max_length=65)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album')),
            ],
        ),
    ]
