# Generated by Django 5.0.1 on 2024-01-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('path', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
