# Generated by Django 5.0.1 on 2024-04-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='background_image',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='album',
            name='preview_image',
            field=models.CharField(default='', max_length=45),
        ),
    ]
