# Generated by Django 5.0.1 on 2024-01-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_album_alter_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.album'),
            preserve_default=False,
        ),
    ]
