# Generated by Django 5.0.1 on 2024-01-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_song_album_id_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='path',
        ),
    ]
