# Generated by Django 5.0.1 on 2024-04-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_album_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='path',
        ),
        migrations.RemoveField(
            model_name='album',
            name='preview_image',
        ),
    ]
