# Generated by Django 5.0.1 on 2024-01-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_song_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_name',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=65),
        ),
    ]
