# Generated by Django 5.0.1 on 2024-01-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_song_file_name_alter_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_name',
            new_name='audio_file_name',
        ),
        migrations.AddField(
            model_name='song',
            name='lyric_sheet_file_name',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
        migrations.AddField(
            model_name='song',
            name='tab_file_name',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
    ]
