# Generated by Django 5.0.1 on 2024-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_album_downloadable_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_player_html',
            field=models.CharField(default='', max_length=650),
            preserve_default=False,
        ),
    ]
