# Generated by Django 5.0.1 on 2024-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_song_album_player_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_player_html',
        ),
        migrations.AddField(
            model_name='album',
            name='display_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
