# Generated by Django 5.0.1 on 2024-03-30 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_song_album_player_html_album_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
