# Generated by Django 5.0.1 on 2024-03-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_guestbookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
