# Generated by Django 5.0.1 on 2024-03-31 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_guestbookentry_user_uuid_alter_guestbookentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
