# Generated by Django 5.0.1 on 2024-03-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_guestbookentry_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
