# Generated by Django 5.0.1 on 2024-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_guestbookentry_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
