# Generated by Django 5.0.1 on 2024-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_guestbookentry_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='time',
            field=models.CharField(default='', max_length=13),
        ),
    ]
