# Generated by Django 5.0.1 on 2024-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_guestbookentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
